import { html, useState, useRef, useMemo, useEffect } from "../../lib.js";

/* ── Persistent recent emojis ──────────────────────────────── */
const RECENT_KEY = "mrd-recent-emojis";
const MAX_RECENT = 24;

function loadRecent() {
  try { return JSON.parse(localStorage.getItem(RECENT_KEY) || "[]"); } catch { return []; }
}
function persistRecent(emoji) {
  const prev = loadRecent();
  const next = [emoji, ...prev.filter((e) => e !== emoji)].slice(0, MAX_RECENT);
  try { localStorage.setItem(RECENT_KEY, JSON.stringify(next)); } catch {}
  return next;
}

/* ── Emoji dataset ─────────────────────────────────────────── */
/* Format per entry: [emoji, "keyword1 keyword2 ..."] (FR + EN) */

const CAT_SMILEYS = { id: "smileys", icon: "😀", label: "Émoticônes", emojis: [
  ["😀","sourire smile heureux happy"],
  ["😃","sourire smile grand big"],
  ["😄","sourire rire laugh"],
  ["😁","sourire dents grin teeth"],
  ["😆","rire laugh"],
  ["😅","sueur rire sweat laugh"],
  ["🤣","rire sol mort floor laugh"],
  ["😂","larmes rire cry laugh tears"],
  ["🙂","léger sourire slight smile"],
  ["😊","sourire yeux smile eyes blush"],
  ["😇","ange angel halo"],
  ["🥰","amour love coeur heart"],
  ["😍","yeux coeur love heart eyes"],
  ["🤩","étoile star excited yeux eyes"],
  ["😘","bisou kiss"],
  ["😗","bisou kiss"],
  ["😚","bisou fermé eyes kiss"],
  ["😙","bisou sourire kiss smile"],
  ["🥲","sourire larme smile tear"],
  ["😋","délicieux yummy tongue"],
  ["😛","langue tongue out"],
  ["😜","clin oeil langue wink tongue"],
  ["🤪","fou silly crazy"],
  ["😝","langue fermé tongue closed eyes"],
  ["🤑","argent money dollar rich"],
  ["🤗","câlin hug"],
  ["🤭","chut oops hand mouth"],
  ["🤫","chut shush quiet"],
  ["🤔","réfléchir think hmm"],
  ["🤐","bouche fermée zip mouth"],
  ["🤨","sourcil eyebrow skeptical"],
  ["😐","neutre neutral"],
  ["😑","sans expression expressionless"],
  ["😶","sans bouche no mouth silent"],
  ["😏","sourire malin smirk"],
  ["😒","bof unamused"],
  ["🙄","yeux ciel eye roll"],
  ["😬","grimace nervous"],
  ["🥸","déguisement disguise nerd"],
  ["😮","surprise surprised open mouth"],
  ["😯","choc wow hushed"],
  ["😲","abasourdi astonished"],
  ["😳","honte blush flushed"],
  ["🥺","please pitié regard puppy eyes"],
  ["😦","soucieux frowning worried"],
  ["😧","angoissé anguished"],
  ["😨","effrayé scared fearful"],
  ["😰","angoisse anxiety cold sweat"],
  ["😥","déçu disappointed sweat"],
  ["😢","pleur cry tear"],
  ["😭","sanglot sob cry loud"],
  ["😱","cri scream horror"],
  ["😖","confus confused"],
  ["😣","effort persévère struggle"],
  ["😞","déçu disappointed"],
  ["😓","sueur déception dejected"],
  ["😩","épuisé weary tired"],
  ["😫","fatigué tired"],
  ["🥱","bâillement yawn sleepy"],
  ["😤","vapeur steam mad"],
  ["😡","colère angry mad"],
  ["😠","colère angry"],
  ["🤬","jurons rage cursing angry"],
  ["😈","démon evil grin imp"],
  ["👿","diable devil angry"],
  ["💀","crâne skull death"],
  ["☠️","tête mort skull crossbones poison"],
  ["🤡","clown"],
  ["👻","fantôme ghost halloween"],
  ["👽","alien extraterrestre"],
  ["🤖","robot"],
  ["💩","caca poop"],
  ["🥳","fête party birthday"],
  ["🤯","esprit soufflé mind blown"],
  ["😷","masque mask malade sick covid"],
  ["🤒","malade thermomètre sick ill"],
  ["🤕","blessé bandage hurt injury"],
  ["🤢","malade nausée sick nausea"],
  ["🤮","vomi vomit sick"],
  ["🤧","éternuement sneeze sick"],
  ["🥵","chaud hot warm"],
  ["🥶","froid cold frozen"],
  ["🥴","étourdi dizzy woozy"],
  ["😵","étourdi knocked out"],
  ["💤","sommeil sleep zzz"],
  ["💥","explosion boom"],
  ["💢","colère anger"],
  ["💦","sueur eau water sweat"],
  ["💨","vent air wind"],
  ["💫","vertige star dizzy"],
  ["✨","étincelles sparkles star"],
  ["🌟","étoile brillante star"],
  ["⭐","étoile star"],
]};

const CAT_PEOPLE = { id: "people", icon: "👤", label: "Personnes", emojis: [
  ["👋","salut bonjour hello wave"],
  ["🤚","main levée raised hand"],
  ["🖐️","main ouverte open hand"],
  ["✋","stop main hand"],
  ["👌","ok parfait"],
  ["🤌","chef kiss"],
  ["✌️","victoire peace v"],
  ["🤞","croiser doigts fingers crossed luck"],
  ["🤟","je t'aime love you"],
  ["🤘","rock cornes"],
  ["👈","gauche left pointer"],
  ["👉","droite right pointer"],
  ["👆","haut up point"],
  ["👇","bas down point"],
  ["☝️","index point one"],
  ["👍","pouce bien like"],
  ["👎","pouce bas dislike unlike"],
  ["✊","poing fist"],
  ["👊","coup poing punch"],
  ["👏","applaudir clap"],
  ["🙌","mains levées hands up celebration"],
  ["🙏","prière prier pray thanks merci"],
  ["✍️","écrire write signature"],
  ["💅","vernis nail polish"],
  ["🤳","selfie"],
  ["💪","muscle bras fort strong"],
  ["👀","yeux eyes regarder look"],
  ["👁️","œil eye"],
  ["🧒","enfant child"],
  ["👦","garçon boy"],
  ["👧","fille girl"],
  ["🧑","adulte person"],
  ["👨","homme man"],
  ["👩","femme woman"],
  ["🧓","senior personne âgée elder"],
  ["👴","vieux grand-père old man grandfather"],
  ["👵","vieille grand-mère old woman grandmother"],
  ["👮","policier police officer"],
  ["👷","ouvrier construction worker"],
  ["💂","garde guard"],
  ["🕵️","détective detective"],
  ["👨‍⚕️","médecin docteur doctor homme"],
  ["👩‍⚕️","médecin docteure doctor femme nurse"],
  ["👨‍🎓","étudiant diplômé graduate student"],
  ["👩‍🎓","étudiante diplômée graduate student"],
  ["👨‍🏫","professeur enseignant teacher man"],
  ["👩‍🏫","professeure enseignante teacher woman"],
  ["👨‍⚖️","juge judge man"],
  ["👩‍⚖️","juge judge woman"],
  ["👨‍🌾","fermier farmer man"],
  ["👩‍🌾","fermière farmer woman"],
  ["👨‍🍳","cuisinier chef cook man"],
  ["👩‍🍳","cuisinière chef cook woman"],
  ["👨‍🔧","mécanicien technicien mechanic man"],
  ["👩‍🔧","mécanicienne mechanic woman"],
  ["👨‍💼","homme bureau manager office"],
  ["👩‍💼","femme bureau manager office"],
  ["👨‍🔬","scientifique chercheur scientist man"],
  ["👩‍🔬","scientifique chercheuse scientist woman"],
  ["👨‍🎨","artiste artist painter man"],
  ["👩‍🎨","artiste artist painter woman"],
  ["👨‍🚒","pompier firefighter man"],
  ["👩‍🚒","pompière firefighter woman"],
  ["👨‍✈️","pilote pilot man"],
  ["👩‍✈️","pilote pilot woman"],
  ["👨‍🚀","astronaute astronaut man"],
  ["👩‍🚀","astronaute astronaut woman"],
  ["🧙","magicien wizard sorcier"],
  ["🧚","fée fairy"],
  ["🧛","vampire"],
  ["🧜","sirène mermaid"],
  ["🧝","elfe elf"],
  ["🦸","super-héros superhero"],
  ["🦹","super-vilain supervillain"],
  ["🤶","mère noël santa mrs"],
  ["🎅","père noël santa christmas"],
  ["💆","massage relaxation spa"],
  ["💇","coiffure haircut"],
  ["🏃","course run courir jog"],
  ["🚶","marche walk"],
  ["🧘","yoga méditation meditation zen"],
  ["💃","danseuse dance"],
  ["🕺","danseur dance"],
  ["👫","couple man woman"],
  ["👬","deux hommes couple gay"],
  ["👭","deux femmes couple lesbian"],
]};

const CAT_FAMILY = { id: "family", icon: "🏠", label: "Famille & Maison", emojis: [
  ["👨‍👩‍👦","famille garçon family boy"],
  ["👨‍👩‍👧","famille fille family girl"],
  ["👨‍👩‍👧‍👦","famille family"],
  ["👪","famille family"],
  ["👶","bébé baby"],
  ["🧒","enfant child"],
  ["👦","garçon boy"],
  ["👧","fille girl"],
  ["👨","père papa father dad"],
  ["👩","mère maman mother mom"],
  ["👴","grand-père grandfather"],
  ["👵","grand-mère grandmother"],
  ["🏠","maison house home"],
  ["🏡","maison jardin house garden home"],
  ["🏘","maisons quartier houses"],
  ["🏗","chantier construction building"],
  ["🏢","immeuble building office"],
  ["🏥","hôpital hospital"],
  ["🏫","école school"],
  ["🏪","magasin shop store"],
  ["🚪","porte door"],
  ["🪟","fenêtre window"],
  ["🛋","canapé sofa couch"],
  ["🛏","lit bed sleep"],
  ["🪑","chaise chair"],
  ["🛁","bain baignoire bath"],
  ["🚿","douche shower"],
  ["🚽","toilettes toilet"],
  ["🪞","miroir mirror"],
  ["🧹","balai balayer clean sweep broom"],
  ["🧺","panier linge laundry basket"],
  ["🪣","seau bucket eau water"],
  ["🧽","éponge sponge clean"],
  ["🫧","bulles savon soap bubbles"],
  ["🧴","lotion savon gel bottle"],
  ["🧻","papier toilette toilet paper"],
  ["🪥","brosse dents toothbrush"],
  ["🪒","rasoir razor"],
  ["🔑","clé key"],
  ["🗝","vieille clé old key"],
  ["🛒","chariot courses shopping cart"],
  ["🛍","sac courses shopping bag"],
  ["📦","boîte carton box package"],
  ["🗑","poubelle trash bin"],
  ["🧱","brique mur wall brick"],
  ["🔧","clé outil wrench tool"],
  ["🔨","marteau hammer"],
  ["🪛","tournevis screwdriver"],
  ["🔩","vis boulon bolt screw"],
  ["🪚","scie saw"],
  ["⚙️","engrenage gear settings"],
  ["🔌","prise plug electricity"],
  ["💡","ampoule lumière light bulb idea"],
  ["🕯","bougie candle"],
  ["🪴","plante plant"],
  ["🌱","pousse plant sprout"],
  ["💐","fleurs flowers"],
  ["🌹","rose flower"],
  ["🌻","tournesol sunflower"],
  ["🪜","échelle ladder"],
  ["🧲","aimant magnet"],
  ["🛠","outils tools"],
  ["🎁","cadeau gift present"],
]};

const CAT_ANIMALS = { id: "animals", icon: "🐶", label: "Animaux", emojis: [
  ["🐶","chien dog"],
  ["🐱","chat cat"],
  ["🐭","souris mouse"],
  ["🐹","hamster"],
  ["🐰","lapin rabbit"],
  ["🦊","renard fox"],
  ["🐻","ours bear"],
  ["🐼","panda"],
  ["🐨","koala"],
  ["🐯","tigre tiger"],
  ["🦁","lion"],
  ["🐮","vache cow"],
  ["🐷","cochon pig"],
  ["🐸","grenouille frog"],
  ["🐵","singe monkey"],
  ["🙈","singe voir monkey"],
  ["🐔","poulet poule chicken"],
  ["🐧","pingouin manchot penguin"],
  ["🐦","oiseau bird"],
  ["🐤","poussin chick"],
  ["🦆","canard duck"],
  ["🦅","aigle eagle"],
  ["🦉","hibou owl"],
  ["🦇","chauve-souris bat"],
  ["🐺","loup wolf"],
  ["🐗","sanglier boar"],
  ["🐴","cheval horse"],
  ["🦄","licorne unicorn"],
  ["🐝","abeille bee"],
  ["🦋","papillon butterfly"],
  ["🐌","escargot snail"],
  ["🐞","coccinelle ladybug"],
  ["🐜","fourmi ant"],
  ["🕷","araignée spider"],
  ["🦂","scorpion"],
  ["🐢","tortue turtle"],
  ["🐍","serpent snake"],
  ["🦎","lézard lizard"],
  ["🦕","dinosaure diplodocus"],
  ["🦖","t-rex dinosaure"],
  ["🐊","crocodile alligator"],
  ["🦈","requin shark"],
  ["🐬","dauphin dolphin"],
  ["🐳","baleine whale"],
  ["🦭","phoque seal"],
  ["🐟","poisson fish"],
  ["🐠","poisson tropical clown fish"],
  ["🦐","crevette shrimp"],
  ["🦞","homard lobster"],
  ["🦀","crabe crab"],
  ["🐙","pieuvre poulpe octopus"],
  ["🐓","coq rooster"],
  ["🦃","dinde turkey"],
  ["🦚","paon peacock"],
  ["🦜","perroquet parrot"],
  ["🦢","cygne swan"],
  ["🦩","flamant rose flamingo"],
  ["🕊","colombe dove peace pigeon"],
  ["🐇","lapin rabbit"],
  ["🦝","raton laveur raccoon"],
  ["🦦","loutre otter"],
  ["🦥","paresseux sloth"],
  ["🐿","écureuil squirrel chipmunk"],
  ["🦔","hérisson hedgehog"],
  ["🐾","pattes empreintes paw prints"],
  ["🐉","dragon"],
  ["🦋","papillon butterfly"],
  ["🌸","cerisier sakura cherry blossom spring"],
]};

const CAT_FOOD = { id: "food", icon: "🍕", label: "Nourriture", emojis: [
  ["🍎","pomme apple fruit"],
  ["🍐","poire pear fruit"],
  ["🍊","orange fruit"],
  ["🍋","citron lemon fruit"],
  ["🍌","banane banana fruit"],
  ["🍉","pastèque watermelon fruit"],
  ["🍇","raisin grapes fruit"],
  ["🍓","fraise strawberry fruit"],
  ["🫐","myrtille blueberry fruit"],
  ["🍑","pêche peach fruit"],
  ["🍒","cerise cherry fruit"],
  ["🥭","mangue mango fruit"],
  ["🍍","ananas pineapple fruit"],
  ["🥥","noix coco coconut"],
  ["🥝","kiwi fruit"],
  ["🍅","tomate tomato"],
  ["🥑","avocat avocado"],
  ["🍆","aubergine eggplant légume"],
  ["🥔","pomme terre potato légume"],
  ["🥕","carotte carrot légume"],
  ["🌽","maïs corn légume"],
  ["🌶","piment chili épicé"],
  ["🥒","concombre cucumber légume"],
  ["🥦","brocoli broccoli légume"],
  ["🧄","ail garlic"],
  ["🧅","oignon onion"],
  ["🥬","salade laitue lettuce légume"],
  ["🫒","olive"],
  ["🍞","pain bread"],
  ["🥐","croissant petit-déjeuner breakfast"],
  ["🥖","baguette bread"],
  ["🥨","bretzel pretzel"],
  ["🧀","fromage cheese"],
  ["🥚","œuf egg"],
  ["🍳","œuf frit fried egg cuisson"],
  ["🥞","crêpes pancakes petit-déjeuner"],
  ["🧇","gaufre waffle"],
  ["🥓","bacon"],
  ["🥩","viande steak meat"],
  ["🍗","poulet cuisses chicken"],
  ["🍖","os viande drumstick"],
  ["🌭","hot dog"],
  ["🍔","burger hamburger"],
  ["🍟","frites fries"],
  ["🍕","pizza"],
  ["🌮","taco"],
  ["🌯","wrap burrito"],
  ["🥙","sandwich falafel"],
  ["🥪","sandwich"],
  ["🍱","bento boîte lunch"],
  ["🍜","ramen soupe nouilles noodles"],
  ["🍝","pâtes pasta spaghetti"],
  ["🍛","curry riz rice"],
  ["🍣","sushi"],
  ["🍤","crevette tempura frit"],
  ["🦪","huître oyster"],
  ["🥗","salade salad"],
  ["🫕","fondue pot raclette"],
  ["🍦","glace ice cream"],
  ["🍧","sorbet"],
  ["🍩","donut beignet"],
  ["🍪","cookie biscuit"],
  ["🎂","gâteau anniversaire birthday cake"],
  ["🍰","part gâteau cake"],
  ["🧁","cupcake"],
  ["🥧","tarte pie"],
  ["🍫","chocolat chocolate"],
  ["🍬","bonbon candy sweet"],
  ["🍭","sucette lollipop"],
  ["🍯","miel honey"],
  ["☕","café coffee"],
  ["🍵","thé tea"],
  ["🫖","théière teapot"],
  ["🧃","jus juice"],
  ["🥤","soda boisson drink"],
  ["🧋","boba bubble tea"],
  ["🍷","vin wine"],
  ["🍸","cocktail"],
  ["🍺","bière beer"],
  ["🥛","lait milk"],
  ["💧","eau water"],
  ["🍾","champagne fête celebration"],
]};

const CAT_ACTIVITIES = { id: "activities", icon: "⚽", label: "Activités", emojis: [
  ["⚽","football soccer"],
  ["🏀","basketball"],
  ["🏈","football américain"],
  ["⚾","baseball"],
  ["🎾","tennis"],
  ["🏐","volley volleyball"],
  ["🏉","rugby"],
  ["🎱","billard billiards pool"],
  ["🏓","ping-pong tennis table"],
  ["🏸","badminton"],
  ["🥊","boxe boxing gant"],
  ["🥋","arts martiaux judo karaté"],
  ["🛹","skateboard"],
  ["⛸","patinage glace ice skating"],
  ["🏒","hockey glace"],
  ["🏊","natation nager swim"],
  ["🤽","water polo"],
  ["🚴","vélo cycling"],
  ["🏋️","musculation haltères weightlifting gym"],
  ["🤸","gymnaste gymnastics"],
  ["🧗","escalade climbing"],
  ["🚵","vélo montagne VTT mountain bike"],
  ["🏃","course courir run jog"],
  ["🚶","marche walk"],
  ["🧘","yoga méditation meditation"],
  ["💃","danse danseuse dance"],
  ["🕺","danse danseur dance"],
  ["🎿","ski"],
  ["🤿","plongée diving snorkel"],
  ["🎯","cible fléchettes darts target"],
  ["🎮","jeux vidéo gaming controller"],
  ["🎲","jeux dés dice board game"],
  ["🧩","puzzle jigsaw"],
  ["♟","échecs chess"],
  ["🎭","théâtre theater drama"],
  ["🎨","peinture art painting dessin"],
  ["✏️","crayon pencil dessin draw"],
  ["📚","livres books étude study"],
  ["📖","livre book lire read"],
  ["🎵","musique music note"],
  ["🎶","notes musique music"],
  ["🎸","guitare guitar"],
  ["🎹","piano clavier"],
  ["🥁","batterie drums"],
  ["🎺","trompette trumpet"],
  ["🎻","violon violin"],
  ["🎤","micro chant sing microphone"],
  ["🎧","casque musique headphones"],
  ["🎬","cinéma film movie"],
  ["📷","photo photographie camera"],
  ["🏆","trophée trophy prize"],
  ["🥇","médaille or gold medal"],
  ["🥈","médaille argent silver medal"],
  ["🥉","médaille bronze"],
  ["🎪","cirque circus"],
  ["🧶","tricot knitting laine"],
  ["🧵","couture sewing thread"],
  ["🪴","jardinage garden plante"],
  ["🌱","jardinage garden planter"],
  ["🏄","surf surfing"],
  ["🤺","escrime fencing"],
  ["🏇","équitation cheval horse riding"],
  ["🎰","casino jeu machine"],
  ["🃏","cartes cards jeu game"],
  ["🀄","mahjong"],
]};

const CAT_TRAVEL = { id: "travel", icon: "✈️", label: "Voyage & Lieux", emojis: [
  ["✈️","avion plane airplane voyage travel"],
  ["🚀","fusée rocket"],
  ["🚂","train locomotive"],
  ["🚆","train"],
  ["🚇","métro metro subway"],
  ["🚉","gare station train"],
  ["🚌","bus"],
  ["🚎","trolley bus"],
  ["🚐","minibus van"],
  ["🚗","voiture car"],
  ["🚕","taxi"],
  ["🚙","SUV voiture car"],
  ["🏎","voiture course race car"],
  ["🏍","moto motorcycle"],
  ["🛵","scooter"],
  ["🚲","vélo bicycle"],
  ["🛴","trottinette scooter"],
  ["🚑","ambulance"],
  ["🚒","camion pompier fire truck"],
  ["🚓","police voiture police car"],
  ["🚚","camion truck"],
  ["🚜","tracteur tractor"],
  ["🚁","hélicoptère helicopter"],
  ["🛶","canoë canoe kayak"],
  ["⛵","voilier sailboat"],
  ["🚢","navire ship cruise"],
  ["🧳","valise bagage luggage travel"],
  ["🗺","carte map"],
  ["🧭","boussole compass navigation"],
  ["🏔","montagne neige mountain snow"],
  ["⛰","montagne mountain"],
  ["🌋","volcan volcano"],
  ["🏕","camping tente tent"],
  ["🏖","plage beach"],
  ["🏜","désert desert"],
  ["🏝","île island"],
  ["🏞","parc park nature"],
  ["🏟","stade stadium"],
  ["🏛","musée monument museum"],
  ["🗼","tour eiffel paris tour"],
  ["🗽","statue liberté liberty"],
  ["🏰","château castle"],
  ["🏯","château japonais castle"],
  ["⛩","torii temple japon"],
  ["🕌","mosquée mosque"],
  ["⛪","église church"],
  ["🌍","europe afrique globe earth"],
  ["🌎","amériques globe earth"],
  ["🌏","asie globe earth"],
  ["🌐","globe internet world"],
  ["🏙","ville city"],
  ["🌃","nuit ville night city"],
  ["🌄","lever soleil sunrise"],
  ["🌅","coucher lever soleil horizon"],
  ["🌉","pont bridge nuit"],
  ["⛽","essence carburant fuel station"],
  ["🚧","travaux construction"],
  ["🗓","calendrier agenda calendar"],
  ["🎫","billet ticket"],
  ["🛂","passeport passport"],
  ["🏄","surf plage beach"],
]};

const CAT_OBJECTS = { id: "objects", icon: "💡", label: "Objets", emojis: [
  ["📱","téléphone smartphone phone mobile"],
  ["💻","ordinateur laptop computer"],
  ["🖥","ordinateur bureau desktop"],
  ["⌨","clavier keyboard"],
  ["🖱","souris ordinateur mouse"],
  ["📷","appareil photo camera"],
  ["📹","caméra vidéo video camera"],
  ["📺","télévision TV screen"],
  ["📻","radio"],
  ["🔋","batterie battery"],
  ["🔌","prise plug charger"],
  ["💡","ampoule lumière light bulb idea"],
  ["🔦","lampe torche flashlight"],
  ["🕯","bougie candle"],
  ["💊","pilule médicament medicine pill"],
  ["💉","seringue injection syringe"],
  ["🩹","pansement bandage blessure"],
  ["🩺","stéthoscope médecin doctor"],
  ["🩼","béquille crutch"],
  ["💰","sac argent money bag"],
  ["💳","carte bancaire credit card"],
  ["💎","diamant diamond gem"],
  ["⚖","balance justice poids"],
  ["🔧","clé anglaise wrench"],
  ["🔨","marteau hammer"],
  ["🛠","outils tools"],
  ["⛏","pioche pickaxe"],
  ["🪚","scie saw"],
  ["🔩","vis boulon bolt screw"],
  ["🪛","tournevis screwdriver"],
  ["🔗","chaîne lien link chain"],
  ["📎","trombone paperclip"],
  ["📌","punaise pin thumbtack"],
  ["✂","ciseaux scissors"],
  ["🔒","cadenas fermé lock secure"],
  ["🔓","cadenas ouvert unlock"],
  ["🔑","clé key"],
  ["🗝","vieille clé old key"],
  ["🪓","hache axe"],
  ["🛡","bouclier shield"],
  ["🧲","aimant magnet"],
  ["⚗","flacon bécher flask"],
  ["🔭","télescope telescope"],
  ["🔬","microscope laboratory"],
  ["📦","boîte carton box colis"],
  ["🎁","cadeau gift present"],
  ["🎀","ruban nœud ribbon bow"],
  ["🎊","confettis party"],
  ["🎉","fête party celebration"],
  ["🎈","ballon balloon"],
  ["📣","mégaphone speaker"],
  ["🔔","cloche bell notification"],
  ["📝","notes memo bloc-notes"],
  ["📋","presse-papiers clipboard"],
  ["📊","graphique chart graph"],
  ["📈","hausse croissance growth chart up"],
  ["📉","baisse decline chart down"],
  ["📁","dossier folder"],
  ["📂","dossier ouvert folder open"],
  ["📅","calendrier date calendar"],
  ["📆","calendrier calendar"],
  ["✏","crayon pencil écrire"],
  ["🖊","stylo pen"],
  ["🖌","pinceau brush"],
  ["🖍","crayon couleur crayon"],
  ["📚","livres books"],
  ["📖","livre book"],
  ["🗑","poubelle trash"],
  ["🧯","extincteur fire extinguisher"],
  ["🛢","baril barrel"],
  ["💸","argent bills money"],
  ["💵","billet dollar bill"],
  ["💶","euro billet"],
]};

const CAT_NATURE = { id: "nature", icon: "🌿", label: "Nature", emojis: [
  ["☀","soleil sun"],
  ["🌤","soleil nuage partly cloudy"],
  ["⛅","nuage soleil cloudy"],
  ["☁","nuage cloud"],
  ["🌧","pluie rain"],
  ["⛈","orage storm thunder"],
  ["🌩","foudre éclair lightning"],
  ["🌨","neige snow"],
  ["❄","flocon neige snowflake ice"],
  ["☃","bonhomme neige snowman"],
  ["🌬","vent wind"],
  ["💨","vent rafale wind"],
  ["🌊","vague wave ocean"],
  ["💧","goutte eau water drop"],
  ["💦","eau water"],
  ["🌈","arc-en-ciel rainbow"],
  ["⚡","éclair lightning bolt orage"],
  ["🔥","feu fire"],
  ["🌙","lune moon nuit"],
  ["🌝","pleine lune full moon"],
  ["🌞","soleil sourire sun warm"],
  ["⭐","étoile star"],
  ["🌟","étoile brillante glowing star"],
  ["✨","étincelles sparkles"],
  ["🌱","pousse herbe plant sprout"],
  ["🌿","herbe herb plant"],
  ["🍀","trèfle clover luck"],
  ["🌸","fleur cerisier cherry blossom spring"],
  ["🌺","hibiscus flower"],
  ["🌻","tournesol sunflower"],
  ["🌹","rose flower"],
  ["🌷","tulipe tulip"],
  ["💐","bouquet flowers"],
  ["🍁","feuille érable autumn maple leaf"],
  ["🍂","feuille tombée fallen leaf autumn"],
  ["🍃","feuilles leaves"],
  ["🌾","blé wheat grain"],
  ["🌵","cactus desert"],
  ["🎄","sapin noël christmas tree"],
  ["🌲","pin arbre conifère pine tree"],
  ["🌳","arbre tree"],
  ["🌴","palmier palm tree"],
  ["🍄","champignon mushroom"],
  ["🐚","coquillage shell plage"],
  ["🪸","corail coral"],
  ["🪨","rocher rock stone"],
  ["🪵","bûche bois log wood"],
  ["⛰","montagne mountain"],
  ["🌋","volcan volcano"],
  ["🏔","montagne enneigée mountain snow"],
  ["🌅","lever coucher soleil sunrise sunset"],
  ["🌄","lever soleil sunrise mountains"],
  ["🌍","terre monde earth globe"],
  ["🌊","mer océan sea ocean"],
  ["🌬","vent air wind"],
  ["🌀","cyclone tornado spiral"],
  ["🌂","parapluie umbrella pluie rain"],
  ["☂","parapluie umbrella"],
  ["🌡","thermomètre température temperature"],
]};

const CAT_SYMBOLS = { id: "symbols", icon: "❤️", label: "Symboles", emojis: [
  ["❤","cœur rouge red heart love amour"],
  ["🧡","cœur orange heart"],
  ["💛","cœur jaune yellow heart"],
  ["💚","cœur vert green heart"],
  ["💙","cœur bleu blue heart"],
  ["💜","cœur violet purple heart"],
  ["🖤","cœur noir black heart"],
  ["🤍","cœur blanc white heart"],
  ["🤎","cœur marron brown heart"],
  ["💔","cœur brisé broken heart"],
  ["💕","deux cœurs hearts love"],
  ["💞","cœurs amour hearts love"],
  ["💖","cœur brillant sparkling heart"],
  ["💘","cœur flèche heart arrow love"],
  ["💝","cœur cadeau heart gift"],
  ["✅","validé coche check ok"],
  ["❌","croix erreur X cross error"],
  ["✔","coche check mark"],
  ["⭕","cercle OK circle"],
  ["🔴","rouge red circle"],
  ["🟠","orange circle"],
  ["🟡","jaune yellow circle"],
  ["🟢","vert green circle"],
  ["🔵","bleu blue circle"],
  ["🟣","violet purple circle"],
  ["⚫","noir black circle"],
  ["⚪","blanc white circle"],
  ["🔶","losange orange diamond"],
  ["🔷","losange bleu blue diamond"],
  ["🔺","triangle rouge red"],
  ["🔻","triangle rouge inversé down"],
  ["⚠","alerte avertissement warning"],
  ["🚫","interdit non banned no"],
  ["♻","recyclage recycle"],
  ["💯","cent pour cent 100 perfect"],
  ["🆗","OK"],
  ["🆕","nouveau new"],
  ["🔝","top"],
  ["♾","infini infinity"],
  ["➕","plus add"],
  ["➖","moins minus"],
  ["➗","division divide"],
  ["✖","multiplication fois times"],
  ["▶","play lecture"],
  ["⏩","avance rapide fast forward"],
  ["⏪","retour rapide rewind"],
  ["⏸","pause"],
  ["⏹","stop arrêt"],
  ["⏺","enregistrement record"],
  ["🔀","aléatoire shuffle"],
  ["🔁","répéter repeat"],
  ["🔃","répéter rotation clockwise"],
  ["🔔","cloche notification bell"],
  ["🔕","silence mute bell"],
  ["ℹ","information info"],
  ["🌐","internet web globe"],
  ["🔗","lien link"],
  ["🔒","verrouillé locked secure"],
  ["🔓","déverrouillé unlocked"],
  ["📶","signal wifi bars"],
  ["🎵","musique music note"],
  ["🎶","notes musique"],
  ["🎊","fête party confettis"],
  ["🎉","fête party celebration"],
  ["🏳","drapeau blanc white flag"],
  ["🏴","drapeau noir black flag"],
  ["🚩","drapeau rouge red flag"],
  ["🏁","drapeau damier finish flag"],
  ["🎌","drapeaux flags"],
  ["🇫🇷","france drapeau flag français"],
]};

/* ── Combined dataset + search index ──────────────────────── */
const ALL_CATS = [CAT_SMILEYS, CAT_PEOPLE, CAT_FAMILY, CAT_ANIMALS, CAT_FOOD, CAT_ACTIVITIES, CAT_TRAVEL, CAT_OBJECTS, CAT_NATURE, CAT_SYMBOLS];

const SEARCH_INDEX = ALL_CATS.flatMap((cat) =>
  cat.emojis.map(([emoji, keywords]) => ({ emoji, kw: keywords.toLowerCase() }))
);

/* ── Component ─────────────────────────────────────────────── */
export function EmojiPicker({ onSelect, onClose }) {
  const [query, setQuery] = useState("");
  const [activeCat, setActiveCat] = useState("smileys");
  const [recent, setRecent] = useState(loadRecent);
  const searchRef = useRef(null);

  useEffect(() => {
    // Auto-focus search on open, small delay for mobile
    const t = setTimeout(() => searchRef.current && searchRef.current.focus(), 80);
    return () => clearTimeout(t);
  }, []);

  const searchResults = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (!q) return null;
    const terms = q.split(/\s+/).filter(Boolean);
    const seen = new Set();
    const result = [];
    SEARCH_INDEX.forEach(({ emoji, kw }) => {
      if (seen.has(emoji)) return;
      if (terms.every((term) => kw.includes(term))) {
        seen.add(emoji);
        result.push(emoji);
      }
    });
    return result;
  }, [query]);

  function handleSelect(emoji) {
    const next = persistRecent(emoji);
    setRecent(next);
    onSelect(emoji);
  }

  const catTabs = [
    { id: "recent", icon: "🕐", label: "Récents", emojis: recent },
    ...ALL_CATS.map((c) => ({ id: c.id, icon: c.icon, label: c.label, emojis: c.emojis.map(([e]) => e) })),
  ];

  const displayEmojis = query.trim()
    ? (searchResults || [])
    : (catTabs.find((c) => c.id === activeCat)?.emojis || []);

  const gridLabel = query.trim()
    ? (searchResults === null ? "" : `${searchResults.length} résultat${searchResults.length !== 1 ? "s" : ""}`)
    : catTabs.find((c) => c.id === activeCat)?.label || "";

  return html`
    <div
      style=${{ position: "fixed", inset: 0, zIndex: 9999, display: "flex", alignItems: "flex-end", justifyContent: "center", background: "oklch(0% 0 0 / 0.45)" }}
      onClick=${onClose}
    >
      <div
        style=${{ background: "var(--mrd-surf)", borderRadius: "20px 20px 0 0", width: "100%", maxWidth: 520, maxHeight: "72vh", display: "flex", flexDirection: "column", overflow: "hidden", paddingBottom: "env(safe-area-inset-bottom, 0px)" }}
        onClick=${(e) => e.stopPropagation()}
      >
        <!-- Drag handle -->
        <div style=${{ width: 36, height: 4, borderRadius: 2, background: "var(--mrd-border)", margin: "10px auto 6px", flexShrink: 0 }} />

        <!-- Search bar -->
        <div style=${{ padding: "0 14px 8px", flexShrink: 0 }}>
          <div style=${{ display: "flex", alignItems: "center", gap: 8, background: "var(--mrd-surf2)", border: "1.5px solid var(--mrd-border)", borderRadius: 12, padding: "0 12px" }}>
            <span style=${{ fontSize: 14, color: "var(--mrd-fg3)", flexShrink: 0 }}>🔍</span>
            <input
              ref=${searchRef}
              type="text"
              placeholder="Rechercher… house, sport, enfant…"
              value=${query}
              onInput=${(e) => setQuery(e.target.value)}
              style=${{ flex: 1, background: "none", border: "none", padding: "9px 0", fontSize: 16, color: "var(--mrd-fg)", outline: "none", fontFamily: "DM Sans, sans-serif" }}
            />
            ${query ? html`<button type="button" onClick=${() => setQuery("")} style=${{ background: "none", border: "none", cursor: "pointer", fontSize: 14, color: "var(--mrd-fg3)", padding: 0, flexShrink: 0 }}>✕</button>` : null}
          </div>
        </div>

        <!-- Category tabs (hidden during search) -->
        ${!query.trim() ? html`
          <div style=${{ display: "flex", overflowX: "auto", gap: 2, padding: "0 10px 6px", flexShrink: 0, scrollbarWidth: "none" }}>
            ${catTabs.map((cat) => html`
              <button key=${cat.id} type="button"
                onClick=${() => setActiveCat(cat.id)}
                title=${cat.label}
                style=${{
                  flexShrink: 0, padding: "6px 8px", borderRadius: 10, fontSize: 20, border: "none", cursor: "pointer",
                  background: activeCat === cat.id ? "var(--mrd-aLt)" : "transparent",
                  outline: activeCat === cat.id ? "1.5px solid var(--mrd-aMd)" : "none",
                  transition: "background 0.15s", lineHeight: 1, display: "flex", alignItems: "center", justifyContent: "center"
                }}
              >${cat.icon}</button>
            `)}
          </div>
        ` : null}

        <!-- Category label -->
        <div style=${{ padding: "0 14px 4px", fontSize: 11, fontWeight: 700, color: "var(--mrd-fg3)", textTransform: "uppercase", letterSpacing: "0.06em", flexShrink: 0 }}>
          ${gridLabel}
        </div>

        <!-- Emoji grid -->
        <div style=${{ overflowY: "auto", padding: "0 8px 16px", display: "flex", flexWrap: "wrap", gap: 1, alignContent: "flex-start", flex: 1 }}>
          ${displayEmojis.length === 0
            ? html`<div style=${{ padding: "24px 16px", color: "var(--mrd-fg3)", fontSize: 13, textAlign: "center", width: "100%" }}>
                ${query.trim() ? "Aucun emoji trouvé. Essaye un autre mot." : "Aucun emoji récent."}
              </div>`
            : displayEmojis.map((emoji) => html`
              <button
                key=${emoji}
                type="button"
                onClick=${() => handleSelect(emoji)}
                style=${{ width: 44, height: 44, fontSize: 24, border: "none", background: "none", cursor: "pointer", borderRadius: 10, display: "flex", alignItems: "center", justifyContent: "center", transition: "background 0.1s", lineHeight: 1, flexShrink: 0 }}
                onMouseEnter=${(e) => { e.currentTarget.style.background = "var(--mrd-surf2)"; }}
                onMouseLeave=${(e) => { e.currentTarget.style.background = "none"; }}
              >${emoji}</button>
            `)
          }
        </div>
      </div>
    </div>
  `;
}
